## GEREKLİ KÜTÜPHANELERİN İMPORT EDİLMESİ

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
from google.colab import drive
drive.mount("/gdrive")
%cd /gdrive

Mounted at /gdrive
/gdrive


In [4]:
import os
os.chdir("/gdrive/My Drive/")

## VERİ SETİNİN OKUNMASI

In [34]:
df = pd.read_csv("Churn_Modelling.csv")

In [35]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [36]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

## BAĞIMLI VE BAĞIMSIZ DEĞİŞKENLERİN ATANMASI

In [37]:
df  = df.drop(["RowNumber", "CustomerId", "Surname"],axis=1)
y  = df["Exited"]
x  = df.drop(["Exited"],axis=1,inplace=True)
gender = df["Gender"].values
geography = df[["Geography"]].values


In [38]:
gender

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

## CİNSİYETLERİN ENCODE EDİLMESİ 0-1

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
gender = le.fit_transform(gender) 

In [40]:
gender

array([0, 0, 0, ..., 0, 1, 0])

In [41]:
gender_Df = pd.DataFrame(gender,columns=["Gender"])
gender_Df

Gender
0          0
1          0
2          0
3          0
4          0
...      ...
9995       1
9996       1
9997       0
9998       1
9999       0

[10000 rows x 1 columns]

## ÜLKELERİN ENCODE EDİLMESİ

In [42]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [43]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [44]:
geography

array([['France'],
       ['Spain'],
       ['France'],
       ...,
       ['France'],
       ['Germany'],
       ['France']], dtype=object)

In [45]:
ulkeler = ohe.fit_transform(geography).toarray()

In [46]:
ulkeler

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [47]:
ulkeler_Df = pd.DataFrame(ulkeler,columns=["France","Germany","Spain"])
ulkeler_Df

France  Germany  Spain
0        1.0      0.0    0.0
1        0.0      0.0    1.0
2        1.0      0.0    0.0
3        1.0      0.0    0.0
4        0.0      0.0    1.0
...      ...      ...    ...
9995     1.0      0.0    0.0
9996     1.0      0.0    0.0
9997     1.0      0.0    0.0
9998     0.0      1.0    0.0
9999     1.0      0.0    0.0

[10000 rows x 3 columns]

In [48]:
x  = df.drop(["Gender","Geography"],axis=1)
x = pd.concat([ulkeler_Df,gender_Df,x],axis=1)


In [49]:
x

France  Germany  Spain  ...  HasCrCard  IsActiveMember  EstimatedSalary
0        1.0      0.0    0.0  ...          1               1        101348.88
1        0.0      0.0    1.0  ...          0               1        112542.58
2        1.0      0.0    0.0  ...          1               0        113931.57
3        1.0      0.0    0.0  ...          0               0         93826.63
4        0.0      0.0    1.0  ...          1               1         79084.10
...      ...      ...    ...  ...        ...             ...              ...
9995     1.0      0.0    0.0  ...          1               0         96270.64
9996     1.0      0.0    0.0  ...          1               1        101699.77
9997     1.0      0.0    0.0  ...          0               1         42085.58
9998     0.0      1.0    0.0  ...          1               0         92888.52
9999     1.0      0.0    0.0  ...          1               0         38190.78

[10000 rows x 12 columns]

## VERİLERİN EĞİTİM VE TEST OLARAK AYRILMASI

In [50]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=0)


## BAĞIMSIZ DEĞİŞKENLERİN ÖLÇEKLENDİRİLMESİ

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

## GEREKLİ KÜTÜPHANELERİN İMPORT EDİLMESİ

In [52]:
import keras
from keras.models import Sequential
from keras.layers import Dense

## YSA VE KATMANLARIN OLUŞTURULMASI

In [53]:
model = Sequential()
model.add(Dense(6, kernel_initializer= "uniform", activation="relu", input_dim = 12))

In [54]:
model.add(Dense(6, kernel_initializer= "uniform", activation="relu"))

In [55]:
model.add(Dense(1, kernel_initializer= "uniform", activation="sigmoid"))

## MODELİN DERLENMESİ

In [56]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

## MODELİN EĞİTİLMESİ

In [57]:
model.fit(x_train,y_train, epochs=50)

Epoch 1/50
210/210 [==============================] - 0s 1ms/step - loss: 0.5927 - accuracy: 0.7961
Epoch 2/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4414 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4324 - accuracy: 0.7979
Epoch 4/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4287 - accuracy: 0.7979
Epoch 5/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4262 - accuracy: 0.7979
Epoch 6/50
210/210 [==============================] - 0s 928us/step - loss: 0.4240 - accuracy: 0.7979
Epoch 7/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4222 - accuracy: 0.7979
Epoch 8/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.7979
Epoch 9/50
210/210 [==============================] - 0s 932us/step - loss: 0.4189 - accuracy: 0.8039
Epoch 10/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4177 - accuracy: 0.

## TAHMİNLERİN YAPILMASI

In [58]:
tahmin = model.predict(x_test)
tahmin = tahmin > 0.5
tahmin

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

## TAHMİN SONUÇLARI

In [59]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,tahmin)
cm

array([[2550,   67],
       [ 464,  219]])

In [60]:
test_loss, test_accuracy = model.evaluate(x_test,y_test)

104/104 [==============================] - 0s 788us/step - loss: 0.4072 - accuracy: 0.8391


In [61]:
test_loss

0.40715691447257996

In [62]:
test_accuracy

0.839090883731842